# Generated by Django 6.0 on 2025-12-18 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction')),
            ],
            options={
                'db_table': 'raw_webhooks',
                'indexes': [models.Index(fields=['provider', 'provider_reference'], name='raw_webhook_provide_43c476_idx'), models.Index(fields=['processed', 'received_at'], name='raw_webhook_process_0a73e7_idx')],
            },
        ),
    ]
