# Generated by Django 5.2.8 on 2025-11-25 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdislike',
            name='disliked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdislike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlike',
            name='liked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userview',
            name='viewed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userview',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user1', 'is_active'], name='matches_user1_i_011e58_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user2', 'is_active'], name='matches_user2_i_23570b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('user1', 'user2')},
        ),
        migrations.AlterUniqueTogether(
            name='userdislike',
            unique_together={('user', 'disliked_user')},
        ),
        migrations.AddIndex(
            model_name='userlike',
            index=models.Index(fields=['user', 'created_at'], name='user_likes_user_id_7fe51a_idx'),
        ),
        migrations.AddIndex(
            model_name='userlike',
            index=models.Index(fields=['liked_user', 'created_at'], name='user_likes_liked_u_caf628_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlike',
            unique_together={('user', 'liked_user')},
        ),
        migrations.AddIndex(
            model_name='userview',
            index=models.Index(fields=['viewer', 'created_at'], name='user_views_viewer__326542_idx'),
        ),
        migrations.AddIndex(
            model_name='userview',
            index=models.Index(fields=['viewed_user', 'created_at'], name='user_views_viewed__a8c075_idx'),
        ),
    ]
